--
-- PostgreSQL database dump
--

\restrict YMOuZzdXNX9KmsJiPy018G8JeZqM9woMUF8S7bMNuf66j7qCdhQum6EVxFlMutt

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


--
-- Name: firmware_kind_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.firmware_kind_enum AS ENUM (
    'beta',
    'stable'
);


--
-- Name: model_kind_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.model_kind_enum AS ENUM (
    'terminus',
    'core',
    'byod',
    'kindle',
    'trmnl'
);


--
-- Name: playlist_item_repeat_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.playlist_item_repeat_type_enum AS ENUM (
    'none',
    'minute',
    'hour',
    'day',
    'week',
    'month',
    'year'
);


--
-- Name: special_function_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.special_function_enum AS ENUM (
    'identify',
    'sleep',
    'add_wifi',
    'restart_playlist',
    'rewind',
    'send_to_me',
    'none'
);


--
-- Name: wake_reason_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.wake_reason_enum AS ENUM (
    'powercycle',
    'all',
    'EXT0',
    'EXT1',
    'timer',
    'touchpad',
    'ulp',
    'button',
    'uart',
    'wifi',
    'cocpu',
    'cocpu_trap_trig',
    'bt'
);


--
-- Name: wifi_status_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.wifi_status_enum AS ENUM (
    'no_shield',
    'idle_status',
    'no_ssid_avail',
    'scan_completed',
    'connected',
    'connect_failed',
    'connection_lost',
    'disconnected'
);


--
-- Name: rodauth_get_salt(bigint); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.rodauth_get_salt(acct_id bigint) RETURNS text
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE salt text;
BEGIN
SELECT
substr(password_hash, 0, 30) INTO salt
FROM "user_password_hash"
WHERE acct_id = id;
RETURN salt;
END;
$$;


--
-- Name: rodauth_valid_password_hash(bigint, text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.rodauth_valid_password_hash(acct_id bigint, hash text) RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE valid boolean;
BEGIN
SELECT password_hash = hash INTO valid 
FROM "user_password_hash"
WHERE acct_id = id;
RETURN valid;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account (
    id integer NOT NULL,
    name text NOT NULL,
    label text NOT NULL,
    settings jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: device; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.device (
    id integer CONSTRAINT devices_id_not_null NOT NULL,
    friendly_id text,
    label text,
    mac_address text,
    api_key text,
    firmware_version text,
    firmware_beta boolean DEFAULT false CONSTRAINT devices_firmware_beta_not_null NOT NULL,
    wifi integer DEFAULT 0 CONSTRAINT devices_wifi_not_null NOT NULL,
    battery double precision DEFAULT 0 CONSTRAINT devices_battery_not_null NOT NULL,
    refresh_rate integer DEFAULT 900 CONSTRAINT devices_refresh_rate_not_null NOT NULL,
    image_timeout integer DEFAULT 0 CONSTRAINT devices_image_timeout_not_null NOT NULL,
    width integer DEFAULT 0 CONSTRAINT devices_width_not_null NOT NULL,
    height integer DEFAULT 0 CONSTRAINT devices_height_not_null NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT devices_created_at_not_null NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT devices_updated_at_not_null NOT NULL,
    proxy boolean DEFAULT false CONSTRAINT devices_proxy_not_null NOT NULL,
    firmware_update boolean DEFAULT false CONSTRAINT devices_firmware_update_not_null NOT NULL,
    sleep_start_at time without time zone,
    sleep_stop_at time without time zone,
    model_id integer,
    playlist_id integer
);


--
-- Name: device_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.device_log (
    id integer CONSTRAINT device_logs_id_not_null NOT NULL,
    device_id integer CONSTRAINT device_logs_device_id_not_null NOT NULL,
    external_id integer CONSTRAINT device_logs_external_id_not_null NOT NULL,
    message text CONSTRAINT device_logs_message_not_null NOT NULL,
    source_path text CONSTRAINT device_logs_source_path_not_null NOT NULL,
    source_line integer CONSTRAINT device_logs_source_line_not_null NOT NULL,
    retry integer DEFAULT 0 CONSTRAINT device_logs_retry_not_null NOT NULL,
    wifi_signal integer DEFAULT 0 CONSTRAINT device_logs_wifi_signal_not_null NOT NULL,
    wifi_status public.wifi_status_enum DEFAULT 'disconnected'::public.wifi_status_enum CONSTRAINT device_logs_wifi_status_not_null NOT NULL,
    refresh_rate integer DEFAULT 0 CONSTRAINT device_logs_refresh_rate_not_null NOT NULL,
    sleep_duration integer DEFAULT 0 CONSTRAINT device_logs_sleep_duration_not_null NOT NULL,
    firmware_version text CONSTRAINT device_logs_firmware_version_not_null NOT NULL,
    special_function public.special_function_enum DEFAULT 'none'::public.special_function_enum CONSTRAINT device_logs_special_function_not_null NOT NULL,
    wake_reason public.wake_reason_enum DEFAULT 'timer'::public.wake_reason_enum CONSTRAINT device_logs_wake_reason_not_null NOT NULL,
    battery_voltage double precision DEFAULT 0 CONSTRAINT device_logs_battery_voltage_not_null NOT NULL,
    free_heap_size integer DEFAULT 0 CONSTRAINT device_logs_free_heap_size_not_null NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT device_logs_created_at_not_null NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT device_logs_updated_at_not_null NOT NULL,
    max_alloc_size integer DEFAULT 0 CONSTRAINT device_logs_max_alloc_size_not_null NOT NULL
);


--
-- Name: device_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.device_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: devices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.device ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: firmware; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.firmware (
    id integer CONSTRAINT firmwares_id_not_null NOT NULL,
    version text CONSTRAINT firmwares_version_not_null NOT NULL,
    kind public.firmware_kind_enum DEFAULT 'stable'::public.firmware_kind_enum CONSTRAINT firmwares_kind_not_null NOT NULL,
    attachment_data jsonb DEFAULT '{}'::jsonb CONSTRAINT firmwares_attachment_data_not_null NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT firmwares_created_at_not_null NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT firmwares_updated_at_not_null NOT NULL
);


--
-- Name: firmwares_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.firmware ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.firmwares_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: membership; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.membership (
    id integer NOT NULL,
    account_id integer NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: membership_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.membership ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.membership_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: model; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model (
    id integer NOT NULL,
    name text NOT NULL,
    label text NOT NULL,
    description text,
    width integer NOT NULL,
    height integer NOT NULL,
    published_at timestamp without time zone,
    mime_type text DEFAULT 'image/png'::text NOT NULL,
    colors integer DEFAULT 2 NOT NULL,
    bit_depth integer DEFAULT 1 NOT NULL,
    rotation integer DEFAULT 0 NOT NULL,
    offset_x integer DEFAULT 0 NOT NULL,
    offset_y integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    kind public.model_kind_enum DEFAULT 'terminus'::public.model_kind_enum NOT NULL
);


--
-- Name: model_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.model ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.model_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: playlist; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.playlist (
    id integer NOT NULL,
    name text NOT NULL,
    label text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    current_item_id integer
);


--
-- Name: playlist_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.playlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.playlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: playlist_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.playlist_item (
    id integer NOT NULL,
    playlist_id integer NOT NULL,
    screen_id integer NOT NULL,
    "position" integer NOT NULL,
    repeat_interval integer DEFAULT 1 NOT NULL,
    repeat_type public.playlist_item_repeat_type_enum DEFAULT 'none'::public.playlist_item_repeat_type_enum NOT NULL,
    repeat_days integer[] DEFAULT '{}'::integer[] NOT NULL,
    last_day_of_month boolean DEFAULT false NOT NULL,
    start_at timestamp without time zone,
    stop_at timestamp without time zone,
    hidden_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: playlist_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.playlist_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.playlist_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


--
-- Name: screen; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.screen (
    id integer NOT NULL,
    model_id integer NOT NULL,
    label text NOT NULL,
    name text NOT NULL,
    image_data jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: screen_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.screen ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.screen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    status_id integer DEFAULT 1 CONSTRAINT user_status_id_not_null1 NOT NULL,
    name text,
    email public.citext NOT NULL,
    settings jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT valid_email CHECK ((email OPERATOR(public.~) '^[^,;@ \r\n]+@[^,@; \r\n]+\.[^,@; \r\n]+$'::public.citext))
);


--
-- Name: user_active_session_key; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_active_session_key (
    user_id bigint NOT NULL,
    session_id text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_use timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: user_authentication_audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_authentication_audit_log (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    message text NOT NULL,
    metadata jsonb
);


--
-- Name: user_authentication_audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_authentication_audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_authentication_audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_jwt_refresh_key; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_jwt_refresh_key (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    key text NOT NULL,
    deadline timestamp without time zone DEFAULT ((CURRENT_TIMESTAMP)::timestamp without time zone + make_interval(days => 1)) NOT NULL
);


--
-- Name: user_jwt_refresh_key_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_jwt_refresh_key ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_jwt_refresh_key_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_password_hash; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_password_hash (
    id bigint NOT NULL,
    password_hash text NOT NULL
);


--
-- Name: user_recovery_code; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_recovery_code (
    id bigint NOT NULL,
    code text NOT NULL
);


--
-- Name: user_remember_key; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_remember_key (
    id bigint NOT NULL,
    key text NOT NULL,
    deadline timestamp without time zone DEFAULT ((CURRENT_TIMESTAMP)::timestamp without time zone + make_interval(days => 14)) NOT NULL
);


--
-- Name: user_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_status (
    id integer NOT NULL,
    name text NOT NULL
);


--
-- Name: user_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account account_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_name_key UNIQUE (name);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: device_log device_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_log
    ADD CONSTRAINT device_logs_pkey PRIMARY KEY (id);


--
-- Name: device devices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);


--
-- Name: firmware firmwares_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.firmware
    ADD CONSTRAINT firmwares_pkey PRIMARY KEY (id);


--
-- Name: firmware firmwares_version_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.firmware
    ADD CONSTRAINT firmwares_version_key UNIQUE (version);


--
-- Name: membership membership_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership
    ADD CONSTRAINT membership_pkey PRIMARY KEY (id);


--
-- Name: model model_label_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model
    ADD CONSTRAINT model_label_key UNIQUE (label);


--
-- Name: model model_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model
    ADD CONSTRAINT model_name_key UNIQUE (name);


--
-- Name: model model_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model
    ADD CONSTRAINT model_pkey PRIMARY KEY (id);


--
-- Name: playlist_item playlist_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playlist_item
    ADD CONSTRAINT playlist_item_pkey PRIMARY KEY (id);


--
-- Name: playlist playlist_label_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playlist
    ADD CONSTRAINT playlist_label_key UNIQUE (label);


--
-- Name: playlist playlist_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playlist
    ADD CONSTRAINT playlist_name_key UNIQUE (name);


--
-- Name: playlist playlist_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playlist
    ADD CONSTRAINT playlist_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: screen screen_label_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.screen
    ADD CONSTRAINT screen_label_key UNIQUE (label);


--
-- Name: screen screen_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.screen
    ADD CONSTRAINT screen_name_key UNIQUE (name);


--
-- Name: screen screen_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.screen
    ADD CONSTRAINT screen_pkey PRIMARY KEY (id);


--
-- Name: user_active_session_key user_active_session_key_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_active_session_key
    ADD CONSTRAINT user_active_session_key_pkey PRIMARY KEY (user_id, session_id);


--
-- Name: user_authentication_audit_log user_authentication_audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_authentication_audit_log
    ADD CONSTRAINT user_authentication_audit_log_pkey PRIMARY KEY (id);


--
-- Name: user_jwt_refresh_key user_jwt_refresh_key_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_jwt_refresh_key
    ADD CONSTRAINT user_jwt_refresh_key_pkey PRIMARY KEY (id);


--
-- Name: user_password_hash user_password_hash_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_password_hash
    ADD CONSTRAINT user_password_hash_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: user_recovery_code user_recovery_code_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_recovery_code
    ADD CONSTRAINT user_recovery_code_pkey PRIMARY KEY (id, code);


--
-- Name: user_remember_key user_remember_key_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_remember_key
    ADD CONSTRAINT user_remember_key_pkey PRIMARY KEY (id);


--
-- Name: user_status user_status_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_status
    ADD CONSTRAINT user_status_name_key UNIQUE (name);


--
-- Name: user_status user_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_status
    ADD CONSTRAINT user_status_pkey PRIMARY KEY (id);


--
-- Name: account_settings_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX account_settings_index ON public.account USING gin (settings);


--
-- Name: audit_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_at_idx ON public.user_authentication_audit_log USING btree (at);


--
-- Name: audit_user_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_user_at_idx ON public.user_authentication_audit_log USING btree (user_id, at);


--
-- Name: device_logs_device_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX device_logs_device_id_index ON public.device_log USING btree (device_id);


--
-- Name: device_logs_special_function_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX device_logs_special_function_index ON public.device_log USING btree (special_function);


--
-- Name: device_logs_wake_reason_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX device_logs_wake_reason_index ON public.device_log USING btree (wake_reason);


--
-- Name: device_logs_wifi_status_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX device_logs_wifi_status_index ON public.device_log USING btree (wifi_status);


--
-- Name: firmwares_attachment_data_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX firmwares_attachment_data_index ON public.firmware USING gin (attachment_data);


--
-- Name: membership_account_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX membership_account_id_index ON public.membership USING btree (account_id);


--
-- Name: membership_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX membership_user_id_index ON public.membership USING btree (user_id);


--
-- Name: model_kind_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX model_kind_index ON public.model USING btree (kind);


--
-- Name: model_label_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX model_label_index ON public.model USING btree (label);


--
-- Name: model_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX model_name_index ON public.model USING btree (name);


--
-- Name: playlist_item_playlist_id_position_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX playlist_item_playlist_id_position_index ON public.playlist_item USING btree (playlist_id, "position");


--
-- Name: playlist_item_repeat_type_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX playlist_item_repeat_type_index ON public.playlist_item USING btree (repeat_type);


--
-- Name: playlist_item_start_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX playlist_item_start_at_index ON public.playlist_item USING btree (start_at);


--
-- Name: playlist_item_stop_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX playlist_item_stop_at_index ON public.playlist_item USING btree (stop_at);


--
-- Name: screen_image_data_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX screen_image_data_index ON public.screen USING gin (image_data);


--
-- Name: screen_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX screen_name_index ON public.screen USING btree (name);


--
-- Name: user_email_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX user_email_index ON public."user" USING btree (email) WHERE (status_id = ANY (ARRAY[1, 2]));


--
-- Name: user_jwt_refresh_key_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_jwt_refresh_key_user_id_idx ON public.user_jwt_refresh_key USING btree (user_id);


--
-- Name: user_settings_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_settings_index ON public."user" USING gin (settings);


--
-- Name: device_log device_logs_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_log
    ADD CONSTRAINT device_logs_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.device(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: device devices_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT devices_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: device devices_playlist_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT devices_playlist_id_fkey FOREIGN KEY (playlist_id) REFERENCES public.playlist(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: membership membership_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership
    ADD CONSTRAINT membership_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: membership membership_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership
    ADD CONSTRAINT membership_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: playlist playlist_current_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playlist
    ADD CONSTRAINT playlist_current_item_id_fkey FOREIGN KEY (current_item_id) REFERENCES public.playlist_item(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: playlist_item playlist_item_playlist_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playlist_item
    ADD CONSTRAINT playlist_item_playlist_id_fkey FOREIGN KEY (playlist_id) REFERENCES public.playlist(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: playlist_item playlist_item_screen_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playlist_item
    ADD CONSTRAINT playlist_item_screen_id_fkey FOREIGN KEY (screen_id) REFERENCES public.screen(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: screen screen_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.screen
    ADD CONSTRAINT screen_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.model(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: user_active_session_key user_active_session_key_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_active_session_key
    ADD CONSTRAINT user_active_session_key_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: user_authentication_audit_log user_authentication_audit_log_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_authentication_audit_log
    ADD CONSTRAINT user_authentication_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: user_jwt_refresh_key user_jwt_refresh_key_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_jwt_refresh_key
    ADD CONSTRAINT user_jwt_refresh_key_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: user_password_hash user_password_hash_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_password_hash
    ADD CONSTRAINT user_password_hash_id_fkey FOREIGN KEY (id) REFERENCES public."user"(id);


--
-- Name: user_recovery_code user_recovery_code_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_recovery_code
    ADD CONSTRAINT user_recovery_code_id_fkey FOREIGN KEY (id) REFERENCES public."user"(id);


--
-- Name: user_remember_key user_remember_key_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_remember_key
    ADD CONSTRAINT user_remember_key_id_fkey FOREIGN KEY (id) REFERENCES public."user"(id);


--
-- Name: user user_status_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_status_id_fkey FOREIGN KEY (status_id) REFERENCES public.user_status(id);


--
-- PostgreSQL database dump complete
--

\unrestrict YMOuZzdXNX9KmsJiPy018G8JeZqM9woMUF8S7bMNuf66j7qCdhQum6EVxFlMutt

SET search_path TO "$user", public;

INSERT INTO schema_migrations (filename) VALUES
('20250305150912_create_devices.rb'),
('20250324153748_create_device_logs.rb'),
('20250401150503_add_device_proxy_column.rb'),
('20250408143435_add_device_firmware_update_column.rb'),
('20250423143027_add_device_log_max_alloc_size.rb'),
('20250429114320_remove_device_setup_at_column.rb'),
('20250429115049_change_device_column_text_types.rb'),
('20250602132300_add_device_sleep_period.rb'),
('20250609143532_add_firmwares.rb'),
('20250624130848_add_model.rb'),
('20250625103300_remove_model_timestamps.rb'),
('20250625123433_add_playlist.rb'),
('20250625123558_add_device_and_model_playlist_columns.rb'),
('20250625123645_change_device_sleep_end_column.rb'),
('20250625123721_add_screen.rb'),
('20250625123745_add_playlist_item.rb'),
('20250723140212_add_playlist_current_item_foreign_key.rb'),
('20250723140455_add_model_detail_columns.rb'),
('20250730094230_change_model_scale_factor_to_float.rb'),
('20250813132657_add_model_timestamps.rb'),
('20250821094444_add_model_kind_column.rb'),
('20250904100039_drop_model_scale_factor.rb'),
('20250908152041_rename_devices.rb'),
('20250908153411_rename_firmwares.rb'),
('20250908153842_rename_device_logs.rb'),
('20250909142527_alter_model_kinds.rb'),
('20250916111723_add_citext_extension.rb'),
('20250916111947_create_account.rb'),
('20250916112018_create_rodauth_user.rb'),
('20250916112035_create_rodauth_user_password_hash.rb'),
('20250916112116_create_membership.rb');
